#!/bin/sh -e

command=foreground
if ! [ $# = 0 ]; then
	command="$1"
	shift
fi
addconf=
[ ! -f "$HOME/.mdvl/d5man/d5manapi.config" ] || \
			addconf="-config \"$HOME/.mdvl/d5man/d5manapi.config\""
exec /usr/share/mdvl-d5man2/d5manapi/bin/d5manapi_release \
						"$command" $addconf "$@"
