PROJECT = d5manapi
PROJECT_DESCRIPTION = D5Man API Server
PROJECT_VERSION = 2.0.0

DEPS = cowboy yamerl
dep_cowboy_commit = master
dep_yamerl_commit = master
DEP_PLUGINS = cowboy yamerl

include erlang.mk
