#!/bin/sh -e
# D5Man API Start Script 2.0 (c) 2019--2023 Ma_Sys.ma <info@masysma.net>

addconf=
[ ! -f "$HOME/.mdvl/d5man/d5manapi.config" ] || \
				addconf="-config $HOME/.mdvl/d5man/d5manapi"

exec erl -noshell -noinput +Bd -pa /usr/share/mdvl-d5man2/d5manapi \
		-eval "application:ensure_all_started(d5manapi)." $addconf "$@"
